name: Python tests

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.11.4
              uses: actions/setup-python@v3
              with:
                  python-version: '3.11.4'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Load QBO token
              env:
                  QBO_TOKEN: ${{ secrets.QBO_TEST_TOKEN }}
              run: echo "$QBO_TOKEN" > test_token.json
            - name: Run DB migrations
              run: alembic upgrade head
            - name: run tests
              env:
                  QBO_BASE_URL: ${{ secrets.QBO_BASE_URL }}
                  QBO_CLIENT_ID: ${{ secrets.QBO_CLIENT_ID }}
                  QBO_CLIENT_SECRET: ${{ secrets.QBO_CLIENT_SECRET }}
                  QBO_REDIRECT_URI: ${{ secrets.QBO_REDIRECT_URI }}
                  STRIPE_CLIENT_ID: ${{ secrets.STRIPE_CLIENT_ID }}
                  TEST_STRIPE_ACCOUNT_ID: ${{ secrets.TEST_STRIPE_ACCOUNT_ID }}
                  TEST_STRIPE_API_KEY: ${{ secrets.TEST_STRIPE_API_KEY }}
              run: pytest
